import numpy as np
from PIL import Image
import os
import matplotlib.pyplot as plt
from scipy.ndimage import median_filter, uniform_filter

# =============== Configurable Parameters ===============
depth_path = '...'   # Path to the input depth map
output_dir = '...'                 # Output directory

# Virtual parameters for relative terrain construction 
# (Strictly for initial topology modeling; lacks absolute physical scale)
RELATIVE_Z_RANGE = 50.0  # Maps depth to a relative elevation range of 0~50 (customizable for gradient computation)
INVERT_DEPTH = False     # Set to True if network depth logic opposes actual terrain (e.g., valleys appear as ridges)

# =======================================================

def ensure_dir(path):
    """Ensure the target directory exists."""
    if not os.path.exists(path):
        os.makedirs(path)

def save_and_log(arr, path, desc):
    """Save 2D array to txt and print log."""
    np.savetxt(path, arr, fmt="%.4f")
    print(f"{desc} saved to: {path}")

def save_xyz(arr, path, desc):
    """Save XYZ coordinates to txt and print log."""
    np.savetxt(path, arr, fmt="%.2f %.2f %.4f")
    print(f"{desc} saved to: {path}")

if __name__ == "__main__":
    ensure_dir(output_dir)

    # 1. Load Depth Map Prior
    print(">>> Loading monocular depth prior...")
    # Load as grayscale using 'L' mode
    depth_img = Image.open(depth_path).convert('L')
    depth_arr = np.array(depth_img).astype(np.float32)
    h, w = depth_arr.shape
    print(f"--> Depth map dimensions: {h} x {w}")
    print(f"--> Original grayscale range: {depth_arr.min()} ~ {depth_arr.max()}")

    # 2. Map to Relative Elevation
    # Rigorously normalize to [0, 1] range to avoid floating-point errors
    depth_norm = (depth_arr - depth_arr.min()) / (depth_arr.max() - depth_arr.min() + 1e-8)

    # Invert the topological manifold if necessary
    if INVERT_DEPTH:
        depth_norm = 1.0 - depth_norm

    # Map to the specified relative elevation range to generate the initial relative DEM
    elevation_matrix = depth_norm * RELATIVE_Z_RANGE
    print(f"--> Relative elevation range after mapping: {elevation_matrix.min():.2f} ~ {elevation_matrix.max():.2f}")

    # 3. Morphological Post-processing (Smoothing & Denoising)
    print(">>> Performing morphological smoothing and denoising...")
    
    # Median filtering: Removes local impulse noise (salt-and-pepper artifacts)
    elevation_matrix_filtered = median_filter(elevation_matrix, size=4)
    
    # Value clipping: Filters out extreme outlier 'cliff' points potentially generated by the network
    z_min, z_max = np.percentile(elevation_matrix_filtered.ravel(), 2), np.percentile(elevation_matrix_filtered.ravel(), 98)
    elevation_matrix_clipped = np.clip(elevation_matrix_filtered, z_min, z_max)
    
    # Uniform filtering: Ensures smooth continuity of micro-topographic relief
    elevation_matrix_smooth = uniform_filter(elevation_matrix_clipped, size=20)

    # 4. Save Results for Downstream Modules (GSR / PDEC)
    print(">>> Saving relative DEM results...")
    
    # 4.1 Save as 2D matrix
    matrix_path = os.path.join(output_dir, "relative_elevation_matrix.txt")
    save_and_log(elevation_matrix_smooth, matrix_path, "[Relative Elevation 2D Matrix]")

    # 4.2 Save as XYZ point cloud (using pixel coordinates as XY)
    yy, xx = np.meshgrid(np.arange(h), np.arange(w), indexing='ij')
    
    # Note: These XYZ coordinates represent relative topology in pixel space, lacking true geographic coordinates
    xyz_relative = np.column_stack((xx.ravel(), yy.ravel(), elevation_matrix_smooth.ravel()))
    xyz_path = os.path.join(output_dir, "relative_elevation_xyz.txt")
    save_xyz(xyz_relative, xyz_path, "[Relative Terrain XYZ Data]")

    # 5. Visualize Relative DEM
    print(">>> Generating pseudo-color visualization...")
    plt.figure(figsize=(10, 8))
    im = plt.imshow(elevation_matrix_smooth, cmap='jet')
    plt.colorbar(im, label='Relative Elevation (pseudo-scale)')
    plt.title('Initial Relative DEM (From Monocular Prior)')
    plt.axis('off')
    
    vis_path = os.path.join(output_dir, "relative_dem_visualization.png")
    plt.savefig(vis_path, bbox_inches='tight', dpi=300)
    plt.close()
    print(f"--> Relative DEM heatmap saved to: {vis_path}")

    print("✅ Initial relative topology DEM constructed successfully! Ready for the next stage (PC-SDF).")
